config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'clients#index'
  resources :client_profiles
  resources :clients do
    resources :timelogs
    resources :client_profiles
    resources :invoices
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :client_profiles do
    def for_user(user)
      where(user_id: user.id)
    end
  end

  def log_summary
    Timelog::Summary.new(timelogs)
  end

  has_many :timelogs, through: :client_profiles

end

app/models/client_profile.rb
class ClientProfile < ActiveRecord::Base
  has_many :timelogs
  belongs_to :client
  belongs_to :user
end

app/models/timelog.rb
class Timelog < ActiveRecord::Base
  belongs_to :client_profile
  has_one :client, through: :client_profile

  scope :by_week, -> { Timelog::Week.bucket(all) }

  validates_presence_of :date

  def total_hours
    return hours if hours
    return (end_time - begin_time) / 1.hour if end_time && begin_time
    return 0
  end

end

app/models/timelog/bi_monthly.rb
class Timelog::BiMonthly < Timelog::Interval

  def self.bucket(timelogs)
    super do |log|
      if log.date.day < 16
        log.date.beginning_of_month
      else
        log.date.beginning_of_month + 14.days
      end
    end
  end

  def title
    end_of_interval.strftime("%B %e")
  end


  def end_of_interval
    date = start_of_interval
    if date.day == 1
      date.beginning_of_month + 14.days
    else
      date.end_of_month
    end
  end

  def sub_intervals
    ::Timelog::Week.bucket(timelogs)
  end

  def has_sub_intervals?
    true
  end

  def split_with_rule
    true
  end

  def show_client_breakdown?
    true
  end

  def interval_class
    'interval--prominent'
  end

end

app/models/timelog/day.rb
class Timelog::Day < Timelog::Interval
  def self.bucket(timelogs)
    super do |log|
      log.date.midnight
    end
  end

  def title
    timelogs.first.date.strftime("%A")
  end

  def pre_title
    "#{start_of_interval.strftime("%B %e")}"
  end

  def has_pre_title
    true
  end

end

app/models/timelog/interval.rb
class Timelog::Interval
  def self.bucket(timelogs)
    logs = self.bucket_timelogs(timelogs) do |log|
      yield log
    end
    logs.keys.sort.reverse.map do |interval_start|
      self.new(logs[interval_start],interval_start)
    end
  end

  def self.bucket_timelogs(timelogs)
    {}.tap do |logs|
      timelogs.each do |log|
        interval_start = yield log
        logs[interval_start] ||= []
        logs[interval_start] << log
      end
    end
  end

  attr_reader :timelogs, :start_of_interval

  def initialize(timelogs, start_of_interval = nil)
    @timelogs = timelogs.sort_by(&:date)
    @start_of_interval = start_of_interval
  end

  def has_pre_title
    false
  end

  def split_with_rule
    false
  end

  def has_sub_intervals?
    false
  end

  def show_client_breakdown?
    false
  end

  def interval_class
    ''
  end

  def client_breakdown
    {}.tap do |breakdown|
      timelogs.group_by(&:client).each do |client, logs|
        breakdown[client.name] = logs.map(&:total_hours).reduce(:+)
      end
    end.each do |k,v|
      yield k,v
    end
  end

  def per_profile
    [].tap do |hours|
      timelogs.group_by(&:client_profile).each do |profile, logs|
        hours << "#{profile.name} #{logs.map(&:total_hours).reduce(:+)}"
      end
    end.join(", ")
  end

  def total_hours
    @_total_hours ||= calculate_total_hours
  end

  def total_earned
    @_total_earned ||= calculate_total_earned
  end

  def average_rate
    @_average_rate ||= calculate_average_rate
  end

  private

  def calculate_total_hours
    if has_sub_intervals?
      sub_intervals.reduce(0) {|m, s| m + s.total_hours }
    else
      timelogs.map(&:total_hours).reduce(:+)
    end
  end

  def calculate_total_earned
    timelogs.reduce(0) do |total, log|
      rate = log.client_profile.rate || 200

      total + (log.total_hours * rate)
    end
  end

  def calculate_average_rate
    total_earned.to_f / total_hours
  end

end

app/models/timelog/summary.rb
class Timelog::Summary < Timelog::Interval

  def self.bucket(timelogs)
    super do |log|
      true
    end
  end

  def title
    "Total"
  end

  def sub_intervals
    ::Timelog::BiMonthly.bucket(timelogs)
  end

  def has_sub_intervals?
    true
  end

  def split_with_rule
    false
  end

  def show_client_breakdown?
    false
  end

  def interval_class
    'interval--very-prominent'
  end

end

app/models/timelog/week.rb
class Timelog::Week < Timelog::Interval

  def self.bucket(timelogs)
    super do |log|
      log.date.beginning_of_week
    end
  end

  def title
    # "#{start_of_interval.beginning_of_week.strftime("%B %e")}"
  end

  def sub_intervals
    ::Timelog::Day.bucket(timelogs)
  end

  def has_sub_intervals?
    true
  end

  def show_client_breakdown?
    false
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :client_profiles
  has_many :clients, through: :client_profiles
  has_many :timelogs, through: :client_profiles

  def most_recent_client_profile
    timelogs.order("created_at desc").first.client_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/client_profiles_controller.rb
class ClientProfilesController < ApplicationController

  def new
    @client = Client.find(params[:client_id])
    @client_profile = @client.client_profiles.build
  end

  def edit
    @client_profile = ClientProfile.find(params[:id])
  end

  def update
    @client_profile = ClientProfile.find(params[:id])
    @client_profile.update_attributes(params[:client_profile])
    redirect_to clients_path
  end

  def create
    ClientProfile.create!(params[:client_profile].merge(user_id: current_user.id))
    redirect_to clients_path
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  def new
    @client = Client.new
  end

  def show
    @client = Client.find(params[:id])
    # @client_profiles = @client.client_profiles.for_user(current_user)
  end

  def edit
    @client = Cliend.find(params[:id])
  end

  def create
    Client.create!(params[:client])
    redirect_to clients_path
  end


end

app/controllers/invoices_controller.rb
require 'csv'
class InvoicesController < ApplicationController
  respond_to :csv
  def index
    client = Client.find(params[:client_id])
    days = Timelog::Day.bucket(client.timelogs)
    csv_data = CSV.generate do |csv|
      csv << ["Day", "Hours", "Total Earned"]
      days.each do |day|
        csv << [day.start_of_interval.to_date.to_formatted_s(:iso8601), day.total_hours, day.total_earned]
      end
    end
    send_data csv_data
  end
end

app/controllers/timelogs_controller.rb
class TimelogsController < ApplicationController

  def create
    timelog = Timelog.create!(params[:timelog])
    redirect_to client_path(timelog.client)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/client_profiles/_new_rate.html.haml
= rf.number_field :ammount, step: "any"
= rf.number_field :max_hours, step: "any"
= rf.check_box :_destroy

app/views/client_profiles/edit.html.haml
%h1 Edit Client Profile
= bootstrap_form_for(@client_profile) do |f|
  = f.text_field :name
  = f.hidden_field :client_id
  = f.hidden_field :user_id
  = f.number_field :rate
  = f.submit "Update Client Profile"

app/views/client_profiles/new.html.haml
%h1 Add a new Client Profile
= bootstrap_form_for(@client_profile, role: 'add_client_profile_form', url: client_client_profiles_path(@client)) do |f|
  = f.text_field :name
  = f.hidden_field :client_id
  = f.hidden_field :user_id
  = f.submit "Add Client Profile"

app/views/clients/_breakdown.html.haml
.interval__breakdown
  - interval.client_breakdown do |name, hours|
    %strong="#{name}:"
    =" #{hours}"

app/views/clients/_sub_interval.html.haml
- interval.sub_intervals.each_with_index do |sub_interval, index|
  .row.interval.interval--secondary{role: 'interval', class: sub_interval.interval_class}
    .col-sm-3.text-right{role: 'title'}
      - if sub_interval.has_pre_title && index == interval.sub_intervals.size - 1
        %span= sub_interval.pre_title
      = sub_interval.title
    .col-sm-1{role: 'total'}
      = sub_interval.total_hours
    .col-sm-1{role: 'earned'}
      = number_to_currency sub_interval.total_earned
    - if sub_interval.show_client_breakdown?
      .col-lg-7
        = render "breakdown", interval: sub_interval
  - if sub_interval.has_sub_intervals?
    = render "sub_interval", interval: sub_interval
    %br
- if interval.split_with_rule
  %hr

app/views/clients/_summary.html.haml
%div{role: 'summary'}
  .row.interval{role: 'interval_summary', class: summary.interval_class}
    .col-sm-offset-3.col-sm-1{role: 'total'}
      =summary.total_hours
    .col-sm-1{role: 'total'}
      =number_to_currency summary.total_earned
  %hr
  = render "sub_interval", interval: summary

app/views/clients/index.html.haml
= render 'timelogs/add_quick_hour'

%h1 Clients
%h2= link_to "Add Client", new_client_path, role: "add_client"
%table.table{role: 'client_list'}
  - Client.all.each do |client|
    %tr
      %td= link_to client.name, client
      %td= client.client_profiles.for_user(current_user).map {|cp| link_to cp.name, edit_client_client_profile_path(client, cp) }.join(", ").html_safe
      %td= link_to "Add Profile", new_client_client_profile_path(client)
      %td= link_to "Invoice", client_invoices_path(client, format: :csv)
= render 'clients/summary', summary: Timelog::Summary.new(current_user.clients.map(&:timelogs).flatten.uniq)

app/views/clients/new.html.haml
%h1 Add a new client
= bootstrap_form_for(@client, role: 'add_client_form') do |f|
  = f.text_field :name
  = f.submit "Add Client"

app/views/clients/show.html.haml
%h1= @client.name
= render "timelogs/add_hour", client: @client
.row
  .col-6-lg
    = render 'clients/summary', summary: @client.log_summary

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Timekeeper
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  %body

    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{type: 'button', data: { toggle: 'collapse', target: '#' }}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Clients", clients_path, class: 'navbar-brand'

    .container
      = yield

app/views/timelogs/_add_hour.html.haml
= bootstrap_form_for(Timelog.new, url: client_timelogs_path(client), layout: :horizontal) do |f|
  = f.select :client_profile_id, client.client_profiles.for_user(current_user).map {|cp| [cp.name, cp.id] }
  = f.date_field :date, value: Time.now.strftime('%d-%m-%Y')
  = f.number_field :hours, step: "any"
  = f.time_field :begin_time
  = f.time_field :end_time
  = f.text_field :description
  = f.submit "Add Hours"

app/views/timelogs/_add_quick_hour.html.haml
- client = current_user.most_recent_client_profile.client
%h1= "Add hours for #{client.name}"
= bootstrap_form_for(Timelog.new, url: client_timelogs_path(client), layout: :horizontal) do |f|
  = f.select :client_profile_id, client.client_profiles.for_user(current_user).map {|cp| [cp.name, cp.id] }, selected: current_user.most_recent_client_profile.id
  = f.date_field :date
  = f.time_field :begin_time
  = f.time_field :end_time
  = f.submit "Add Hours"